git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never

gui:
  theme:
    activeBorderColor:
      - "#aac7ff"
      - bold
    inactiveBorderColor:
      - "#b0c7f4"
    searchingActiveBorderColor:
      - "#efb0ff"
      - bold
    optionsTextColor:
      - "#c1c6d5"
    selectedLineBgColor:
      - "#c1c6d5"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#c1c6d5"
    cherryPickedCommitBgColor:
      - "#efb0ff"
    markedBaseCommitFgColor:
      - "#efb0ff"
    markedBaseCommitBgColor:
      - "#ffb4ab"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#e1e2eb"
