git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never

gui:
  theme:
    activeBorderColor:
      - "#adcbdd"
      - bold
    inactiveBorderColor:
      - "#bdc8d0"
    searchingActiveBorderColor:
      - "#d8bedd"
      - bold
    optionsTextColor:
      - "#c2c7cb"
    selectedLineBgColor:
      - "#c2c7cb"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#c2c7cb"
    cherryPickedCommitBgColor:
      - "#d8bedd"
    markedBaseCommitFgColor:
      - "#d8bedd"
    markedBaseCommitBgColor:
      - "#ffb4ab"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#e3e2e3"
