git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never

gui:
  theme:
    activeBorderColor:
      - "#dbf0ff"
      - bold
    inactiveBorderColor:
      - "#b3cad9"
    searchingActiveBorderColor:
      - "#fbe7ff"
      - bold
    optionsTextColor:
      - "#c0c7ce"
    selectedLineBgColor:
      - "#c0c7ce"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#c0c7ce"
    cherryPickedCommitBgColor:
      - "#fbe7ff"
    markedBaseCommitFgColor:
      - "#fbe7ff"
    markedBaseCommitBgColor:
      - "#ffb4ab"
    unstagedChangesColor:
      - "#ffb4ab"
    defaultFgColor:
      - "#e1e2e5"
