$wall = /home/mohireza/Downloads/wallpapers/wallhaven-lqqve2_2560x1440.png
# $wall = $HOME/.config/hyprlock/wallpapers/hyprlock.png
$source = Droid Sans
# source = $HOME/.config/hyprlock/fonts/SF Pro Display Bold
# BACKGROUND
background {
    monitor =
    path = $wall
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8916
    vibrancy = 0.8916
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# Profie-Photo
image {
    monitor =
    path = /home/mohireza/.config/hypr/vivek.png
    border_size = 2
    border_color = $primary_3_rgba 
    size = 100
    rounding = -1
    rotate = 0
    reload_time = -1
    reload_cmd = 
    position = 25, 100
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(216, 222, 233, 0.80)
    font_size = 50
    font_family = $source
    position = 30, -30
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(216, 222, 233, .80)
    font_size = 16
    font_family = $source
    position = 35, -100
    halign = center
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 500, 500
    color = rgba(0, 0, 0, 0.7)
    rounding = 15
    blur_passes = 1
    blur_size=3
    border_size = 0
    border_color = $primary_8_rgba 
    rotate = 0
    xray = false 
    position = 34, -70
    halign = center
    valign = center
    opacity = 0.9
}

# # USER-BOX
# shape {
#     monitor =
#     size = 320, 55
#     color = rgba(255, 255, 255, 0.1)
#     rounding = -1
#     border_size = 0
#     border_color = rgba(255, 255, 255, 1)
#     rotate = 0
#     xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)
#
#     position = 34, -200
#     halign = center
#     valign = center
# }

# USER
label {
    monitor =
    text = $USER
    color = rgba(216, 222, 233, 0.80)
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 16
    font_family = $source
    position = 38, -200
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = $source
    placeholder_text = <i><span foreground="##ffffff99">   Enter Pass</span></i>
    hide_input = false
    position = 34, -260
    halign = center
    valign = center
}
